id: IBD4B754D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T17:16:02+00:00'
last_modified: '2022-06-09T08:35:14.121954+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6931
  title: མཆིམས་ཀྱི་རུས་རྒྱུད་སྐོར་བརྗོད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    2A71:
      image_group_id: I3CN6933
      title: Volume 1 of bod kyi gna' rabs mchims kyi rus rgyud skor brjod pa/
      total_pages: 214
      order: 1
      base_file: 2A71.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
